# spring:
#   application:
#     name: userservice
#   config:
#     import: optional:configserver:http://localhost:8888/configserver
server:
  port: 8500
  servlet:
    context-path: /userservice
spring:
  config:
    import: optional:configserver:http://localhost:8888/configserver
spring.jpa:
  hibernate:
    ddl-auto: update
  show-sql: true
  properties:
    hibernate:
      format_sql: true
      use_sql_comments: true
spring.datasource:
  url: jdbc:mysql://localhost:3306/cas
  username: root
  password: root
  driver-class-name: com.mysql.cj.jdbc.Driver
  hikari:
    maximum-pool-size: 10
    minimum-idle: 5
    idle-timeout: 30000
    connection-timeout: 30000
    max-lifetime: 1800000
